In [1]:
import numpy

In [2]:
db=[[1,"armaan","ok"],[2,"zaheer","good"],[3,"naseem","ok"],[4,"samar","ok"]]

In [3]:
db

[[1, 'armaan', 'ok'],
 [2, 'zaheer', 'good'],
 [3, 'naseem', 'ok'],
 [4, 'samar', 'ok']]

In [5]:
a=numpy.array(db)

In [6]:
type(a)

numpy.ndarray

In [7]:
a

array([['1', 'armaan', 'ok'],
       ['2', 'zaheer', 'good'],
       ['3', 'naseem', 'ok'],
       ['4', 'samar', 'ok']], dtype='<U11')

In [8]:
db

[[1, 'armaan', 'ok'],
 [2, 'zaheer', 'good'],
 [3, 'naseem', 'ok'],
 [4, 'samar', 'ok']]

In [9]:
a[:]

array([['1', 'armaan', 'ok'],
       ['2', 'zaheer', 'good'],
       ['3', 'naseem', 'ok'],
       ['4', 'samar', 'ok']], dtype='<U11')

In [10]:
a[:,1]

array(['armaan', 'zaheer', 'naseem', 'samar'], dtype='<U11')

In [11]:
a[:,1:2]

array([['armaan'],
       ['zaheer'],
       ['naseem'],
       ['samar']], dtype='<U11')

In [12]:
a[0]

array(['1', 'armaan', 'ok'], dtype='<U11')

In [13]:
a[0:3]

array([['1', 'armaan', 'ok'],
       ['2', 'zaheer', 'good'],
       ['3', 'naseem', 'ok']], dtype='<U11')

In [14]:
db[:]

[[1, 'armaan', 'ok'],
 [2, 'zaheer', 'good'],
 [3, 'naseem', 'ok'],
 [4, 'samar', 'ok']]

In [15]:
a[:]

array([['1', 'armaan', 'ok'],
       ['2', 'zaheer', 'good'],
       ['3', 'naseem', 'ok'],
       ['4', 'samar', 'ok']], dtype='<U11')

In [16]:
#first before column is row
a[:,1]

array(['armaan', 'zaheer', 'naseem', 'samar'], dtype='<U11')

In [17]:
a[:1]

array([['1', 'armaan', 'ok']], dtype='<U11')

In [18]:
a[:,1:3]

array([['armaan', 'ok'],
       ['zaheer', 'good'],
       ['naseem', 'ok'],
       ['samar', 'ok']], dtype='<U11')

In [19]:
a[1:1,3]

IndexError: index 3 is out of bounds for axis 1 with size 3

In [20]:
a[1:,1:3]

array([['zaheer', 'good'],
       ['naseem', 'ok'],
       ['samar', 'ok']], dtype='<U11')

In [21]:
a[1:3:,1:3]

array([['zaheer', 'good'],
       ['naseem', 'ok']], dtype='<U11')

In [23]:
a.shape

(4, 3)

In [24]:
a1=numpy.array([1,2,3,4,5,6,7,8])

In [25]:
type(a1)

numpy.ndarray

In [26]:
a1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [27]:
a1[2:5]

array([3, 4, 5])

In [28]:
a1.shape

(8,)

In [29]:
a.shape

(4, 3)

In [30]:
type(a)

numpy.ndarray

In [31]:
x=5

In [32]:
x

5

In [33]:
a1.reshape(4,2).shape

(4, 2)

In [34]:
a1.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [35]:
a1.reshape(8,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [36]:
a1.reshape(1,8)

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [42]:
a1.reshape(8,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [43]:
a1.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])