In [1]:
import pandas

In [2]:
db =  pandas.read_csv("marks.csv")

In [3]:
type(db)

pandas.core.frame.DataFrame

In [4]:
db

name  hrs  marks
0  armaan    7     70
1  zaheer    5     50
2   erick    8     80
3   harry    2     20

In [6]:
y=db["marks"]

In [7]:
x=db["hrs"]

In [8]:
x

0    7
1    5
2    8
3    2
Name: hrs, dtype: int64

In [12]:
from sklearn.linear_model import LinearRegression

In [13]:
mind=LinearRegression()

In [14]:
x.shape

(4,)

In [15]:
type(x)

pandas.core.series.Series

In [17]:
x=x.values

In [18]:
type(x)

numpy.ndarray

In [19]:
x= x.reshape(4,1)

In [20]:
x.reshape(4,1).shape

(4, 1)

In [21]:
mind.fit(x,y)

LinearRegression()

In [22]:
x

array([[7],
       [5],
       [8],
       [2]], dtype=int64)

In [23]:
x.shape

(4, 1)

In [24]:
mind.predict([[6]])

array([60.])

In [25]:
mind.coef_

array([10.])

In [26]:
import joblib

In [27]:
joblib.dump(mind , 'marks.pk1')

['marks.pk1']