In [12]:
import pandas

In [13]:
ds = pandas.read_csv("SalaryData.csv")

In [14]:
ds

YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54442.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8  917388.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              9.0  105582.0
25              9.5  116969.0
26              9.6  112635.0
27             10.3  122391.0
28             10.5  121872.0

In [17]:
ds.columns

Index(['YearsExperience', 'Salary'], dtype='object')

In [18]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   YearsExperience  29 non-null     float64
 1   Salary           29 non-null     float64
dtypes: float64(2)
memory usage: 592.0 bytes


In [19]:
x = ds['YearsExperience'].values.reshape(29,1)

In [20]:
y = ds['Salary'].values.reshape(29,1)

In [21]:
from sklearn.linear_model import LinearRegression

In [22]:
model = LinearRegression()

In [23]:
model.fit(x,y)

LinearRegression()

In [24]:
type(x)

numpy.ndarray

In [25]:
x.shape

(29, 1)

In [26]:
model.predict([[1.1]])

array([[40236.92149323]])

In [27]:
40236/39343*100

102.26978115547874

In [28]:
model.predict([[1.5]])

array([[46396.63622958]])

In [29]:
model.coef_

array([[15399.28684088]])

In [30]:
#y = c+wx
#15399 * 1.1
model.predict([[1.1]])

array([[40236.92149323]])

In [31]:
c = model.intercept_

In [32]:
c

array([23297.70596827])

In [33]:
import joblib

In [34]:
joblib.dump(model , 'salary.pk1')

['salary.pk1']